import type { LucideIcon } from "lucide-react"
import {
  ArrowRight,
  Award,
  BadgeCheck,
  Building,
  Check,
  ChevronRight,
  CircleCheck,
  Clock,
  Droplet,
  Droplets,
  Flame,
  House,
  Leaf,
  Mail,
  MapPin,
  Paintbrush,
  Phone,
  Shield,
  Sparkles,
  Star,
  Thermometer,
  ThumbsUp,
  Trophy,
  Truck,
  Users,
  Wind,
  Wrench,
  Zap,
} from "lucide-react"

const ICON_MAP: Record<string, LucideIcon> = {
  arrowRight: ArrowRight,
  award: Award,
  badgeCheck: BadgeCheck,
  building: Building,
  check: Check,
  checkCircle: CircleCheck,
  chevronRight: ChevronRight,
  circleCheck: CircleCheck,
  clock: Clock,
  droplet: Droplet,
  droplets: Droplets,
  flame: Flame,
  home: House,
  house: House,
  leaf: Leaf,
  mail: Mail,
  mapPin: MapPin,
  paintbrush: Paintbrush,
  phone: Phone,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  thermometer: Thermometer,
  thumbsUp: ThumbsUp,
  tool: Wrench,
  trophy: Trophy,
  truck: Truck,
  users: Users,
  wind: Wind,
  wrench: Wrench,
  zap: Zap,
}

/** Returns the Lucide icon component for the given string key, or null. */
export function getIcon(key: string): LucideIcon | null {
  return ICON_MAP[key] ?? null
}
